INSERT INTO BR_LOOKUP_TYPE VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'CONTAINER_TYPES', TRUE, 'CONTAINER_TYPES');
INSERT INTO BR_LOOKUP_TYPE VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'MEDIA_TYPES', TRUE, 'MEDIA_TYPES');
INSERT INTO BR_LOOKUP_TYPE VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'VIDEO_TYPES', TRUE, 'VIDEO_TYPES');

INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'SHOW', 'SHOW', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='CONTAINER_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'MOVIE', 'MOVIE', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='CONTAINER_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'ALBUM', 'ALBUM', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='CONTAINER_TYPES'));

INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'IMAGE ASSET', 'IMAGE_ASSET', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='MEDIA_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'VIDEO ASSET', 'VIDEO_ASSET', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='MEDIA_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'ADVERTISEMENT ASSET', 'ADVERTISEMENT_ASSET', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='MEDIA_TYPES'));

INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'MOVIE VIDEO TYPE', 'MOVIE', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='VIDEO_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'FULL EPISODE VIDEO TYPE', 'FULL_EPISODE', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='VIDEO_TYPES'));
INSERT INTO BR_LOOKUP_DATA VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'FULL CLIP VIDEO TYPE', 'FULL_CLIP', (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='VIDEO_TYPES'));


INSERT INTO BR_MEDIA_CONTAINER VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'SHOW 1', 'SHOW 1', (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='SHOW'));
INSERT INTO BR_MEDIA_CONTAINER VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'SHOW 2', 'SHOW 2', (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='SHOW'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'IMAGE 1', 'HTTP://WWW.GOOGLE.COM/IMAGES', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='IMAGE_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'IMAGE 2', 'HTTP://WWW.GOOGLE.COM/IMAGES', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='IMAGE_ASSET')); 

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'IMAGE 3', 'HTTP://WWW.GOOGLE.COM/IMAGES', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='IMAGE_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'IMAGE 4', 'HTTP://WWW.GOOGLE.COM/IMAGES', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='IMAGE_ASSET'));    


INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'VIDEO 1', 'HTTP://WWW.GOOGLE.COM/VIDEOS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='VIDEO_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'VIDEO 2', 'HTTP://WWW.GOOGLE.COM/VIDEOS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='VIDEO_ASSET')); 

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'VIDEO 3', 'HTTP://WWW.GOOGLE.COM/VIDEOS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='VIDEO_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'VIDEO 4', 'HTTP://WWW.GOOGLE.COM/VIDEOS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='VIDEO_ASSET'));



INSERT INTO BR_MEDIA_ASSET_VIDEO VALUES((SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='VIDEO 1'), (SELECT ID FROM BR_LOOKUP_DATA LD WHERE LD.LOOKUP_TYPE_ID = (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='VIDEO_TYPES') AND LD.NAME='MOVIE'));

INSERT INTO BR_MEDIA_ASSET_VIDEO VALUES((SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='VIDEO 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='FULL_EPISODE'));

INSERT INTO BR_MEDIA_ASSET_VIDEO VALUES((SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='VIDEO 3'), (SELECT ID FROM BR_LOOKUP_DATA LD WHERE LD.LOOKUP_TYPE_ID = (SELECT ID FROM BR_LOOKUP_TYPE WHERE NAME='VIDEO_TYPES') AND LD.NAME='MOVIE'));
INSERT INTO BR_MEDIA_ASSET_VIDEO VALUES((SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='VIDEO 4'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='FULL_CLIP'));


INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'AD 1', 'HTTP://WWW.GOOGLE.COM/ADS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='ADVERTISEMENT_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'AD 2', 'HTTP://WWW.GOOGLE.COM/ADS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 1'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='ADVERTISEMENT_ASSET')); 

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'AD 3', 'HTTP://WWW.GOOGLE.COM/ADS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='ADVERTISEMENT_ASSET'));

INSERT INTO BR_MEDIA_ASSET VALUES(RANDOM_UUID(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP(), 'AD 4', 'HTTP://WWW.GOOGLE.COM/ADS', (SELECT ID FROM BR_MEDIA_CONTAINER WHERE NAME='SHOW 2'), (SELECT ID FROM BR_LOOKUP_DATA WHERE NAME='ADVERTISEMENT_ASSET'));

INSERT INTO BR_MEDIA_ASSET_ADVERTISEMENT VALUES('BOTTLEROCKET AD 1 PRODUCT DESCRIPTION ', (SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='AD 1'));

INSERT INTO BR_MEDIA_ASSET_ADVERTISEMENT VALUES('BOTTLEROCKET AD 2 PRODUCT DESCRIPTION', (SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='AD 2'));

INSERT INTO BR_MEDIA_ASSET_ADVERTISEMENT VALUES('BOTTLEROCKET AD 3 PRODUCT DESCRIPTION', (SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='AD 3'));

INSERT INTO BR_MEDIA_ASSET_ADVERTISEMENT VALUES('BOTTLEROCKET AD 4 PRODUCT DESCRIPTION', (SELECT ID FROM BR_MEDIA_ASSET WHERE NAME='AD 4'));